// Generated by CoffeeScript 1.7.1
(function() {
  var Walker, game, randomInt;

  game = {
    init: function() {
      console.log("Game Init");
      this.canvas = document.getElementById('canvas');
      this.context = canvas.getContext('2d');
      return this.walker = new Walker(this, 100, 100);
    },
    update: function() {
      return this.walker.step();
    },
    render: function() {
      console.log('RENDER');
      return this.walker.display();
    },
    gameLoop: function() {
      this.update();
      this.render();
      return window.requestAnimationFrame(((function(_this) {
        return function() {
          return _this.gameLoop();
        };
      })(this)));
    }
  };

  randomInt = function(max) {
    return Math.floor(Math.random() * max);
  };

  Walker = (function() {
    function Walker(game_, x_, y_) {
      this.game = game_;
      this.x = x_;
      this.y = y_;
    }

    Walker.prototype.display = function() {
      this.game.context.fillStyle = "#ff0000";
      return this.game.context.fillRect(this.x, this.y, 5, 5);
    };

    Walker.prototype.step = function() {
      var choice;
      choice = randomInt(4);
      switch (choice) {
        case 0:
          return this.x += 5;
        case 1:
          return this.x -= 5;
        case 2:
          return this.y += 5;
        case 3:
          return this.y -= 5;
      }
    };

    return Walker;

  })();

  window.addEventListener("load", function() {
    game.init();
    return game.gameLoop();
  });

}).call(this);
