// Generated by CoffeeScript 1.7.1
(function() {
  var Walker, game, randomInt;

  game = {
    init: function() {
      console.log("Game Init");
      this.canvas = document.getElementById('canvas');
      this.context = canvas.getContext('2d');
      return this.walker = new Walker(this, 320, 240);
    },
    update: function() {
      return this.walker.step();
    },
    render: function() {
      console.log('RENDER');
      return this.walker.display();
    },
    gameLoop: function() {
      this.update();
      this.render();
      return window.requestAnimationFrame(((function(_this) {
        return function() {
          return _this.gameLoop();
        };
      })(this)));
    }
  };

  randomInt = function(min, max) {
    return Math.floor(Math.random() * (max - min) + min);
  };

  Walker = (function() {
    function Walker(game_, x_, y_) {
      this.game = game_;
      this.x = x_;
      this.y = y_;
    }

    Walker.prototype.display = function() {
      this.game.context.fillStyle = "#ff0000";
      return this.game.context.fillRect(this.x, this.y, 5, 5);
    };

    Walker.prototype.step = function() {
      var stepX, stepY;
      stepX = (randomInt(0, 3) - 1) * 5;
      stepY = (randomInt(0, 3) - 1) * 5;
      this.x += stepX;
      return this.y += stepY;
    };

    return Walker;

  })();

  window.addEventListener("load", function() {
    game.init();
    return game.gameLoop();
  });

}).call(this);
